---
# tasks file for rabbitmq-exporter
- name: rabbitmq-exporter | installation.
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_items:
    - svc.yml
    - secret.yml
    - deploy.yml
