---
# tasks file for node-exporter
- name: node-exporter | installation.
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_items:
    - svc.yml
    - sa.yml
    - daemonset.yml
