- name: devops-web  | Create a service for devops-web
  k8s: 
    state: "{{ mds_app_state }}"
    definition: "{{ lookup('template', 'devops-web.svc.yml') | from_yaml }}"

- name: devops-web  | Create a deploy for devops-web
  k8s: 
    state: "{{ mds_app_state }}"
    definition: "{{ lookup('template', 'devops-web.deploy.yml') | from_yaml }}"

- name: devops-web  | Create a ingress for devops-web
  k8s: 
    state: "{{ mds_app_state }}"
    definition: "{{ lookup('template', 'devops-web.ingress.yml') | from_yaml }}"

