- name: devops-gateway  | Create a service for devops-gateway
  k8s: 
    state: "{{ mds_app_state }}"
    definition: "{{ lookup('template', 'devops-gateway.svc.yml') | from_yaml }}"

- name: devops-gateway  | Create a deploy for devops-gateway
  k8s: 
    state: "{{ mds_app_state }}"
    definition: "{{ lookup('template', 'devpos-gateway.deploy.yml') | from_yaml }}"


