apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-eureka
  namespace: {{ mds_app_namespace }}
spec:
  selector:
    matchLabels:
      app: devops-eureka
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devops-eureka
    spec:
      nodeSelector:
        {{ devops_eureka_nodeselector_key }}: {{ devops_eureka_nodeselector_value }}
      tolerations:
        - key: {{ devops_eureka_tolerate_key }}
          operator: Exists
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx512m
        envFrom:
        - configMapRef:
            name: devops-cnfmap
        image: {{ devops_eureka_image }}
        imagePullPolicy: IfNotPresent
        name: devops-eureka
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: {{ image_pull_secret }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

