apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-exporter-cm-{{ influxdb_ip }}
  namespace: {{ exporter_namespace }}
  labels:
    app: influxdb-exporter-{{ influxdb_ip }}
data:
  telegraf.conf: |+
    [global_tags]
    [agent]
      interval = "15s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"

      flush_interval = "10s"
      flush_jitter = "0s"

      precision = ""
      debug = false
      quiet = false
      hostname = ""
      omit_hostname = false

    [[outputs.prometheus_client]]
      listen = ":9273"
    [[inputs.influxdb]]
      urls = [
        "$INFLUXDB_ADDR/debug/vars"
      ]

