apiVersion: v1
kind: Service
metadata:
  name: influxdb-exporter-{{ influxdb_ip }}
  namespace: {{ exporter_namespace }}
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: influxdb-exporter-{{ influxdb_ip }}
    category: DataBase
    env: {{ env }}
    group: {{ influxdb_group }}
    projectCode: {{ influxdb_projectCode }}
    type: Influxdb
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9273
      targetPort: metrics
  selector:
    app.kubernetes.io/name: influxdb-exporter-{{ influxdb_ip }}

