apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: mds-mds
    chart: prometheus-9.3.1
    heritage: Tiller
  name: alertmanager
  namespace: {{ prometheus_stack_namespace }}
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10m
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: {{ alertmanager_webhook }}
        send_resolved: true

