apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: mds-mds
    chart: prometheus-9.3.1
    heritage: Tiller
  name: alertmanager
  namespace: {{ prometheus_stack_namespace }}

