apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: mds-mds
    chart: prometheus-9.3.1
    heritage: Tiller
  name: alertmanager
  namespace: {{ prometheus_stack_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
  storageClassName: prometheus-storage

