# pv
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-storage-pv
  labels:
    type: local
spec:
  storageClassName: prometheus-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/grafana"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.kubernetes.io/prometheus"
              operator: "Exists"

