apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: grafana
  namespace: {{ prometheus_stack_namespace }}
  labels:
    app: grafana
    chart: grafana-4.0.2
    heritage: Tiller
    release: mds-mds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
  namespace: {{ prometheus_stack_namespace }}
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: {{ prometheus_stack_namespace }}

