apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: {{ prometheus_stack_namespace}}
  labels:
    app: grafana
    chart: grafana-4.0.2
    release: mds-mds
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "c3Ryb25ncGFzc3dvcmQ="
  ldap-toml: ""

