apiVersion: v1
kind: Service
metadata:
  labels:
    component: "server"
    app: prometheus
    release: mds-mds
  name: prometheus-headless
  namespace: {{ prometheus_stack_namespace }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    component: "server"
    app: prometheus
    release: mds-mds

