apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "server"
    app: prometheus
    release: mds-mds
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ prometheus_stack_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus

