apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: mds-mds
    chart: prometheus-9.3.1
    heritage: Tiller
  name: mds-prometheus-pushgateway
subjects:
  - kind: ServiceAccount
    name: mds-prometheus-pushgateway
    namespace: {{ prometheus_stack_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mds-prometheus-pushgateway


