apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    component: "pushgateway-flink"
    app: prometheus-flink
    release: mds-mds
    chart: prometheus-9.3.1
    heritage: Tiller
  name: pushgateway-flink
rules: []

