apiVersion: v1
kind: Service
metadata:
  name: graylog-http
  namespace: {{ graylog_namespace }}
  labels:
    name: graylog
spec:
  selector:
    graylog: "true"
  ports:
  - name: graylog-http
    protocol: TCP
    port: 9000
  type: ClusterIP

