apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog-master
  namespace: {{ graylog_namespace }}
spec:
  serviceName: "graylog-master"
  replicas: 1
  selector:
    matchLabels:
      graylog: "true"
      role: graylog-master
  template:
    metadata:
      labels:
        role: graylog-master
        graylog: "true"
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - graylog-master
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: graylog-master
          image: graylog/graylog:4.1
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: GRAYLOG_PASSWORD_SECRET
            value: "KLiJ9Qfl0yg39ST2i4copvOemrC9nhByqK2qyQ1Vws6V7hbv4O1I7PvELiHlmePK21qOnmE4msSv0M1F3I8AAZFk12A2I6DO"
          - name: GRAYLOG_ROOT_PASSWORD_SHA2                   #Password: Graylog@123.com
            value: "f1986caf3e93027866caf104e067117df0deb6a7f943010b6e53fa359794de36"
          - name: GRAYLOG_MONGODB_URI
            value: {{ GRAYLOG_MONGODB_URI }}
          - name: GRAYLOG_ELASTICSEARCH_HOSTS
            value: "http://elasticsearch:9200"
          - name: GRAYLOG_ROOT_TIMEZONE
            value: "PRC"
          - name: GRAYLOG_IS_MASTER
            value: "true"
          - name: GRAYLOG_ALLOW_HIGHLIGHTING
            value: "true"
          - name: GRAYLOG_MESSAGE_JOURNAL_MAX_AGE
            value: "12h"
          - name: GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE
            value: "10gb"
          - name: GRAYLOG_STALE_MASTER_TIMEOUT
            value: "20000"
          - name: GRAYLOG_REST_LISTEN_URI
            value: "http://0.0.0.0:9000/api/"
          - name: GRAYLOG_WEB_LISTEN_URI
            value: "http://0.0.0.0:9000/"
          - name: GRAYLOG_REST_TRANSPORT_URI
            value: "http://graylog-master:9000/api/"
          - name: GRAYLOG_WEB_ENDPOINT_URI
            value: "http://{{ graylog_ingress }}/api/"                  ####域名信息
          - name: GRAYLOG_HTTP_PUBLISH_URI
            value: "http://{{ graylog_ingress }}/"                      ####域名信息
          - name: GRAYLOG_SERVER_JAVA_OPTS
            value: "-Xms2g -Xmx2g -XX:NewRatio=1 -XX:MaxMetaspaceSize=512m -server -XX:+ResizeTLAB -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"    ####内存信息
          - name: GRAYLOG_HTTP_ENABLE_GZIP
            value: "true"
          - name: GRAYLOG_ELASTICSEARCH_SOCKET_TIMEOUT
            value: "60s"
          - name: GRAYLOG_PROCESSBUFFER_PROCESSORS
            value: "5"
          - name: GRAYLOG_OUTPUTBUFFER_PROCESSORS
            value: "5"
          ports:
          - containerPort: 9000
            name: graylog-http
            protocol: TCP
          - containerPort: 3333
            protocol: UDP
            name: gelf-udp-input
          - containerPort: 5044
            protocol: TCP
            name: beats-tcp-input
          volumeMounts:
          - name: local-storage
            mountPath: /usr/share/graylog/data/journal
          resources:
            limits:
            requests:
              cpu: 1
              memory: 3Gi
              cpu: 500m
              memory: 3Gi
          livenessProbe:
            httpGet:
              path: /api/system/lbstatus
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 2
      nodeSelector:
        key: graylog-master
      tolerations:
      - key: es-data
        effect: "NoSchedule"
      volumes:
      - name: local-storage
        hostPath:
          path: /data/graylog

