apiVersion: v1
kind: Service
metadata:
  name: graylog-slave
  namespace: {{ graylog_namespace }}
  labels:
    name: graylog-slave
spec:
  selector:
    role: graylog-slave
  ports:
  - name: http
    protocol: TCP 
    port: 9000
  type: ClusterIP
