apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: emqx-exporter
  namespace: mds
  labels:
    app.kubernetes.io/name: emqx-exporter
data:
  #default emqx admin password - public
  #echo -n emqx-password | base64
  admin_password: {{ admin_password | b64encode }}

