apiVersion: v1
kind: Service
metadata:
  name: emqx-exporter
  namespace: {{ exporter_namespace }}
  annotations:
    prometheus.io/port: "9540"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: emqx-exporter
    category: BigData
    env: {{ env }}
    group: {{ group }}
    projectCode: {{ projectCode }}
    type: Emqx
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9540
      targetPort: metrics
  selector:
    app.kubernetes.io/name: emqx-exporter

