apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-exporter
  namespace: {{ exporter_namespace }}
  labels:
    app.kubernetes.io/name: rabbitmq-exporter
data:
  #echo -n rabbitmq-password | base64
    rabbitmq_password: {{ rabbitmq_password | b64encode }}
  
