apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      nodeSelector:
        zone: mds
      tolerations:
        - key: mds
          operator: Exists
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
          ports:
            - name: metrics
              containerPort: 9308
              protocol: TCP
          resources:
            limits:
              cpu: 120m
              memory: 120Mi
            requests:
              cpu: 60m
              memory: 60Mi

