apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: {{ exporter_namespace }}
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      nodeSelector:
        {{ nodeselector_key }}: {{ nodeselector_value }}
      tolerations:
        - key: {{ tolerate_key }}
          operator: Exists
      containers:
        - name: kafka-exporter
          image: {{ kafka_exporter_image }}
          imagePullPolicy: IfNotPresent
          args:
            {% for server in kafka_sever %}
            - --kafka.server={{ server }}
            {% endfor %}
          ports:
            - name: metrics
              containerPort: 9308
              protocol: TCP
          resources:
            limits:
              cpu: 120m
              memory: 120Mi
            requests:
              cpu: 60m
              memory: 60Mi

