apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: {{ exporter_namespace }}
  annotations:
    prometheus.io/port: "9308"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: kafka-exporter
    category: BigData
    env: {{ env }}
    group: {{ kafka_group }}
    projectCode: {{ kafka_projectCode }}
    type: Kafka
spec:
  type: ClusterIP
  ports:
    - port: 9308
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: kafka-exporter

