- name: alertmanager  | Create a service for alertmanager 
  k8s: 
    state: "{{ alertmanager_state }}"
    definition: "{{ lookup('template', 'alertmanager.svc.yml') | from_yaml }}"

- name: alertmanager | Create a configmap for alertmanager 
  k8s: 
    state: "{{ alertmanager_state }}"
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_items:
    - alertmanager.cm.yml

- name: alertmanager | Create a rbac for alertmanager 
  k8s: 
    state: "{{ alertmanager_state }}"
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_items:
    - alertmanager.sa.yml
    - alertmanager.clusterrolebinding.yml
    - alertmanager.clusterrole.yml

- name: alertmanager | Create a pv and pvc  for alertmanager 
  k8s: 
    state: "{{ alertmanager_state }}"
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_items:
    - alertmanager.pv.yml
    - alertmanager.pvc.yml

- name: alertmanager | Create a deployment for alertmanager 
  k8s: 
    state: "{{ alertmanager_state }}"
    definition: "{{ lookup('template', 'alertmanager.deploy.yml') | from_yaml }}"

- name: alertmanager | Create a ingress for alertmanager 
  k8s: 
    state: "{{ alertmanager_state }}"
    definition: "{{ lookup('template', 'alertmanager.ingress.yml') | from_yaml }}"
