- name: pushgateway-flink  | Create a service for pushgateway-flink 
  k8s: 
    state: present
    definition: "{{ lookup('template', 'pushgateway-flink.svc.yml') | from_yaml }}"

- name: pushgateway-flink | Create a rbac for pushgateway-flink 
  k8s: 
    state: present
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_items:
    - pushgateway-flink.sa.yml
    - pushgateway-flink.clusterrolebinding.yml
    - pushgateway-flink.clusterrole.yml

- name: pushgateway-flink | Create a deployment for pushgateway-flink 
  k8s: 
    state: present
    definition: "{{ lookup('template', 'pushgateway-flink.deploy.yml') | from_yaml }}"
