apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysqld-exporter-{{ mysqld_ip }}
  namespace: {{ exporter_namespace }}
  labels:
    app.kubernetes.io/name: mysqld-exporter-{{ mysqld_ip }}
data:
  # data_source_name="user:password@(hostname:3306)/"
  # echo -n "$data_source_name" | base64
     data_source_name: {{ data_source_name | b64encode }}
  
