apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-exporter-rocketmq-1
  namespace: {{ exporter_namespace }}
  labels:
    app.kubernetes.io/name: rocketmq-exporter-rocketmq-1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: rocketmq-exporter-rocketmq-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rocketmq-exporter-rocketmq-1
    spec:
      nodeSelector:
        {{ nodeselector_key }}: {{ nodeselector_value }}
      tolerations:
        - key: {{ tolerate_key }}
          operator: Exists
      containers:
        - name: exporter
          image: {{ exporter_image }}
          args:
            - --rocketmq.config.namesrvAddr={{ rocketmq_ip }}:9876
            - --rocketmq.config.rocketmqVersion=V4_8_0
          ports:
            - name: metrics
              containerPort: 5557
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 10m
              memory: 20Mi
