apiVersion: v1
kind: Service
metadata:
  name: rocketmq-exporter-rocketmq-1
  namespace: {{ exporter_namespace }}
  annotations:
    prometheus.io/port: "5557"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: rocketmq-exporter-rocketmq-1
    category: BigData
    env: {{ env }}
    group: {{ rocketmq_group }}
    projectCode: {{ rocketmq_projectCode }}
    type: RocketMQ
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 5557
      targetPort: metrics
  selector:
    app.kubernetes.io/name: rocketmq-exporter-rocketmq-1

