apiVersion: v1
kind: Service
metadata:
  name: zookeeper-exporter
  namespace: {{ exporter_namespace }}
  annotations:
    prometheus.io/port: "9141"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: zookeeper-exporter
    category: BigData
    env: {{ env }}
    group: {{ group }}
    projectCode: {{ projectCode }}
    type: Zookeeper
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9141
      targetPort: metrics
  selector:
    app.kubernetes.io/name: zookeeper-exporter

