apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: redis-exporter-<ip.last>
  namespace: mds
  labels:
    app.kubernetes.io/name: redis-exporter-<ip.last>
data:
  # echo -n "$redis-password" | base64
    admin_password: {{ admin_password | b64encode }}
  
