apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: "node-exporter"
    app: prometheus
    release: mds-mds
    chart: prometheus-9.3.1
    heritage: Tiller
    category: Host
    env: {{ env }}
    group: {{ node_group }}
    projectCode: {{ node_projectCode }}
    type: Host
  name: mds-mds-prometheus-node-exporter
  namespace: {{ exporter_namespace }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
    release: mds-mds
  type: "ClusterIP"

